REM for some reason, running the same command twice is sometimes important to "really" delete it...at least on my computer...
rmdir /s /q %USERPROFILE%\.nuget\packages\libsignalservice-uwp
rmdir /s /q %USERPROFILE%\.nuget\packages\libsignalservice-uwp
